### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by mcollina** [smartiniOnGitHub/fastify-cloudevents#1]
Docs are missing.

**Comment by smartiniOnGitHub** [comment]
Sure, I'll add something ASAP. Thanks for the initial review. Bye

**Comment by smartiniOnGitHub** [comment]
Code updated, added README, some examples, etc ... hope now all is good.
First release of the plugin just published at npm, you can find [here](https://www.npmjs.com/package/fastify-cloudevents).
I already have a list of improvements for next release, to be a little more flexible in usage.

Unless objections (or things to fix/improve) I'll close this issue by the end of this week, and raise a PR in fastify to list it in Community Plugins (this release or if there are changes to do, next).
Thanks for now.

**Comment by mcollina** [comment]
This is ok! Go for it!
