### ISSUE TITLE
Use https://github.com/smartiniOnGitHub/cloudevent.js instead?

### ISSUE THREAD

**Issue by mcollina** [smartiniOnGitHub/fastify-cloudevents#2]

**Comment by smartiniOnGitHub** [comment]
Hi Matteo, yes sure, just a quick summary:
I started to develop everything in this repository but then I figured out that it would be better to have the library standalone, for better reuse ... and now that it has been published in its standalone repository (but not yet at npm) I'll remove the code from here and use it.
Thanks for the initial review :-) . Bye

**Comment by smartiniOnGitHub** [comment]
Hi, just refactored the code to use 'cloudevent.js' now, so all is consistent now.
More Fastify-related features will follow soon in the plugin (related to hooks, etc).
